"""empty message

Revision ID: 1b2dd8182888
Revises: 31f1799664b8
Create Date: 2019-12-01 01:34:04.622805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2dd8182888'
down_revision = '31f1799664b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'price')
    # ### end Alembic commands ###
